name       : libgudev
version    : '237'
release    : 10
source     :
    - https://download.gnome.org/sources/libgudev/237/libgudev-237.tar.xz : 0d06b21170d20c93e4f0534dbb9b0a8b4f1119ffb00b4031aaeb5b9148b686aa
license    : LGPL-2.1-or-later
component  : system.base
homepage   : http://wiki.gnome.org/Projects/libgudev
summary    : GObject bindings for libudev
description: |
    GObject bindings for libudev
emul32     : yes
devel      : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(libudev)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi
    %meson_configure -Dintrospection=$build_gobject -Dtests=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
