name       : libgudev
version    : 230
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgudev/230/libgudev-230.tar.xz : a2e77faced0c66d7498403adefcc0707105e03db71a2b2abd620025b86347c18
license    : LGPL-2.1
summary    : GObject bindings for libudev
description: |
    GObject bindings for libudev
builddeps  :
    - pkgconfig(libudev)
    - pkgconfig(glib-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
