name       : libgudev
version    : '233'
release    : 6
source     :
    - https://download.gnome.org/sources/libgudev/233/libgudev-233.tar.xz : 587c4970eb23f4e2deee2cb1fb7838c94a78c578f41ce12cac0a3f4a80dabb03
license    : LGPL-2.1-or-later
summary    : GObject bindings for libudev
component  : system.base
description: |
    GObject bindings for libudev
emul32     : yes
devel      : yes
builddeps  :
    - pkgconfig32(libudev)
    - pkgconfig32(glib-2.0)
setup      : |
    %configure --disable-static --disable-umockdev
build      : |
    %make
install    : |
    %make_install
