name       : libgudev
version    : '232'
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgudev/232/libgudev-232.tar.xz : ee4cb2b9c573cdf354f6ed744f01b111d4b5bed3503ffa956cefff50489c7860
license    : LGPL-2.1
summary    : GObject bindings for libudev
component  : system.base
description: |
    GObject bindings for libudev
builddeps  :
    - pkgconfig32(libudev)
    - pkgconfig32(glib-2.0)
emul32     : yes
devel      : yes
setup      : |
    %configure --disable-static \
               --disable-umockdev
build      : |
    %make
install    : |
    %make_install
