name       : libgudev
version    : '236'
release    : 8
source     :
    - https://download.gnome.org/sources/libgudev/236/libgudev-236.tar.xz : e50369d06d594bae615eb7aeb787de304ebaad07a26d1043cef8e9c7ab7c9524
license    : LGPL-2.1-or-later
component  : system.base
homepage   : http://wiki.gnome.org/Projects/libgudev
summary    : GObject bindings for libudev
description: |
    GObject bindings for libudev
emul32     : yes
devel      : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig32(libudev)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi
    %meson_configure -Dintrospection=$build_gobject -Dtests=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
